// 目录自动创建layout.js 应用程序的主要布局,在页面之间所有共享的UI元素,比如导航，页脚等
export const metadata = {
  
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
